spring:
  redis:
    host: localhost
    port: 6379
    password: Ay1ZwVVeVsHIHnPh0g9LyjQHsOHiqYgWqVsXSZQPAkw=
  main:
    allow-circular-references: true
    
    
server:
  servlet:
    session:
      timeout: 300

  



